# Generated by Django 5.0.6 on 2026-06-27 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_score', models.PositiveSmallIntegerField(default=0, help_text='Overall match % (0–100)')),
                ('ats_score', models.PositiveSmallIntegerField(default=0, help_text='ATS compatibility % (0–100)')),
                ('matching_skills', models.TextField(blank=True, help_text='Newline-separated matching skills')),
                ('missing_skills', models.TextField(blank=True, help_text='Newline-separated missing skills')),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('interview_readiness', models.TextField(blank=True)),
                ('raw_response', models.TextField(blank=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='resume.resume')),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
